### ISSUE TITLE
Stopped: Build more than N seconds

### ISSUE THREAD

**Issue by peacechen** [yongkangchen/atom-ctags#100]
When selecting Rebuild ctags, the following error appears:

Stopped: Build more than N seconds, check if <...> contain too many file.
Suggest that add CmdArgs at atom-ctags package setting, example:
--exclude=some/path --exclude=some/other

I've added the exclusion arguments but atom-ctags doesn't seem to honor them:
--exclude=node_modules --exclude=bower_components

Increased the timeout from default 5 to 30 seconds, still times out.  I placed the Windows build of ctags in my path, and from the command line it rebuilds the tags in under 10 seconds.  Am I not setting the arguments correctly, or doing something else wrong?

Atom 0.205 / atom-ctags 4.1.0 / Win7

**Comment by yongkangchen** [comment]
Fixed in #99, Release in v4.1.1
Please try again
