### ISSUE TITLE
Installing “atom-ctags@4.1.2” failed

### ISSUE THREAD

**Issue by gloomyzerg** [yongkangchen/atom-ctags#104]
Installing “atom-ctags@4.1.2” failed.Hide output…

> ctags@2.1.0 install C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-11559-8120-nxyv1g\node_modules\atom-ctags\node_modules\ctags
> node-gyp rebuild

C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-11559-8120-nxyv1g\node_modules\atom-ctags\node_modules\ctags>node "C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-0.207.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-0.207.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\d-11559-8120-gsavu0\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ctags@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

**Comment by yongkangchen** [comment]
I think it duplicate with https://github.com/atom/node-ctags/issues/10
