### ISSUE TITLE
Im having this problem when trying to install atom-ctags on my windows 8 PC

### ISSUE THREAD

**Issue by admilne** [yongkangchen/atom-ctags#105]
Installing “atom-ctags@4.1.2” failed.Hide output…

> ctags@2.1.0 install C:\Users\ANDRE_~1\AppData\Local\Temp\apm-install-dir-115510-360-1uwnij5\node_modules\atom-ctags\node_modules\ctags
> node-gyp rebuild

C:\Users\ANDRE_~1\AppData\Local\Temp\apm-install-dir-115510-360-1uwnij5\node_modules\atom-ctags\node_modules\ctags>node "C:\Users\andre_000\AppData\Local\atom\app-0.208.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\andre_000\\AppData\\Local\\atom\\app-0.208.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\andre_000\\AppData\\Local\\atom\\app-0.208.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\andre_000\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\andre_000\\.atom\\.apmrc" "install" "C:\\Users\\ANDRE_~1\\AppData\\Local\\Temp\\d-115510-360-12n92xg\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ctags@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

**Comment by yongkangchen** [comment]
see atom/node-ctags#10

**Comment by yongkangchen** [comment]
Fixed in v4.1.4
