### ISSUE TITLE
Work with lua have strange display.

### ISSUE THREAD

**Issue by xpol** [yongkangchen/atom-ctags#118]
![ctags](https://cloud.githubusercontent.com/assets/20248/9399815/2cbfb2fa-47ec-11e5-98ff-e6e4d5c46984.png)

Why there is `/^local ` `/^function` and `$/`

**Comment by yongkangchen** [comment]
懒得去掉，直接把pattern显示出来了:)

**Comment by yongkangchen** [comment]
BTW, 你的luacheck插件，很赞
