### ISSUE TITLE
Make Mouse Operations Configurable

### ISSUE THREAD

**Issue by n3bulous** [yongkangchen/atom-ctags#122]
Referencing https://github.com/yongkangchen/atom-ctags/issues/2 where @contentfree and I bring up alt-click collisions with the [column selection plugin](https://atom.io/packages/sublime-style-column-selection)

ctags and column selection are both extremely useful, but mouse actions don't appear to be configurable on Atom's keybindings preference page.

**Comment by n3bulous** [comment]
You rock! That was unbelievably quick. It was actually keeping me from using Atom in a regular basis. Thank you!

**Comment by contentfree** [comment]
Can you provide a mini-howto on how to adjust this config? Sorry to be dense.

**Comment by contentfree** [comment]
Doesn't seem to work. I tried making it alt+right-click (on OSX). After restarting Atom, alt+right-clicking just shows the normal right-click context menu.

**Comment by yongkangchen** [comment]
@contentfree did not support right-click on OS X.
I guess atom editor show context menu and stop the mouse event propagation.
Please use left-click on OS X instead.
