### ISSUE TITLE
Disable autosuggestion

### ISSUE THREAD

**Issue by brbrr** [yongkangchen/atom-ctags#126]
Due this issue: https://github.com/yongkangchen/atom-ctags/issues/106
Suggestion output become very messy. I would like to have possibility to switch it off if not needed. 
Thanks!

**Comment by littlebee** [comment]
+1  Is there a way to disable the autosuggest but keep the goto symbol functionality?   Goto symbol, even accross a large code base seems to work well, but the autocomplete offers way to many suggestions and trying to type "or", like below, or anything at the end of a comment line is extra painful and usually results in going back and removing a bad autosuggest.  I tried changing it to tab key only, but then you couldn't use it at all.
<img width="607" alt="text_cjsx_-__users_bwilkerson_projects_zulily_htdocs_ems_-_atom" src="https://cloud.githubusercontent.com/assets/593784/10823546/64859822-7e19-11e5-9661-e0eae3007776.png">

**Comment by littlebee** [comment]
Thank you!
