### ISSUE TITLE
Extra text in suggestions

### ISSUE THREAD

**Issue by ProLoser** [yongkangchen/atom-ctags#128]
![image](https://cloud.githubusercontent.com/assets/67395/10528943/9dce75f2-734e-11e5-9ec9-1115b8f28173.png)

As you see in the screenshot, I'm seeing (and for other issues on here) all suggestions are wrapped in `/^ ... $/`

Is it possible to strip this text out?

**Comment by yongkangchen** [comment]
Duplicate with #106

**Comment by yongkangchen** [comment]
Also fixed by f6d6991
