### ISSUE TITLE
return-from-declaration shortcut not working on Mac

### ISSUE THREAD

**Issue by arielpontes** [yongkangchen/atom-ctags#129]
'.platform-darwin atom-text-editor':
      'alt-cmd-up': 'atom-ctags:return-from-declaration'

When I 'alt+click' a name (I'm programming in Python), I am taken to the declaration as expected. When I hit 'alt-cmd-up' to go back though, nothing happens. The Key Binding Resolver doesn't even seem to detect that the "up" key was pressed. It just shows:

    Key Binding Resolver: alt-cmd

The Keybindings list doesn't show any conflict. I tried to investigate if it was some misconfiguration on my end but since I couldn't find anything I'm reporting it as a bug here. Sorry if I missed something.

My solution for now is this custom keybinding:

    '.platform-darwin atom-text-editor':
      'alt-cmd-b': 'atom-ctags:return-from-declaration'

**Comment by yongkangchen** [comment]
I think it conflict with mac shortcut, you should check in mac Sys Preferences - Keyboard
