### ISSUE TITLE
Line numbers always zero

### ISSUE THREAD

**Issue by sronsiek** [yongkangchen/atom-ctags#130]
I have a ctags file generated by exuberant ctags. When I run vim in a terminal, place cursor over a tag & type Ctrl-] it jumps to the correct file and correct position in that file, ie to the line where the definition of the tag is.

In atom with atom-ctags, when I place the mouse over a tag, right-click and select 'Go to declaration' it jumps to the correct file, but to the first line of that file.

When there are multiple tags, these are shown in a drop-down menu. Within this I see the line numbers for all targets are zero.

I have tweaked the key-mappings to get the same key-codes as vim to work, same behaviour.

Is this perhaps a bug or am I doing something wrong?

**Comment by yongkangchen** [comment]
see README:
```
'extraTagFiles' setting, add specified tagFiles.(Make sure you tag file generate with --fields=+KSn)
```

**Comment by sronsiek** [comment]
Yes - the fields arg fixed it (of course). Who needs users, eh?

Thx for the tip!
