### ISSUE TITLE
Project-level Config file

### ISSUE THREAD

**Issue by okonomiyaki3000** [yongkangchen/atom-ctags#143]
I would like to put a config file (`.ctags`) at the root of my project but this doesn't seem to be recognized. If I put one at `~/.ctags`, it works but this is not ideal. Is there a way to use one at the project-level?

**Comment by jch** [comment]
@okonomiyaki3000 I proposed a fix in https://github.com/yongkangchen/atom-ctags/pull/148. If it isn't accepted, you can accomplish something similar by specifying `--options=.ctags` in the preferences for atom-ctags arguments.
