### ISSUE TITLE
Alternative Keybinding for "Go To Declaration"

### ISSUE THREAD

**Issue by jhasse** [yongkangchen/atom-ctags#150]
It seems that "Go To Declaration" is binded to Ctrl+Alt+Down by default. This keybinding is already taken on most Linux system by the desktop environment for switching workspaces.

I suggest the F12 key as an alternative, as this is also the keybinding in Visual Studio.

**Comment by yongkangchen** [comment]
You can custom in your own `keymap.cson` in `Open Your Keymap`
