### ISSUE TITLE
missing CmdArgs option

### ISSUE THREAD

**Issue by despairblue** [yongkangchen/atom-ctags#16]
Using atom-ctags I get:

```
stoped: Build more than 5000 seconds, check if /home/despairblue/vcs/git//kietsy_app contain too many file.
Suggest that add CmdArgs at atom-ctags package setting, example:
--exclude=some/path --exclude=some/other
```

Probably because of the `node_modules` folder. But in the atom-ctags setting there is nothing to set CmdArgs, there is only an option for `Auto Build Tags When Active`

Am I missing something?

Atom 0.114.0
Atom Ctags 2.1.1

**Comment by andywenk** [comment]
this has also happened to me. I am really not sure why. After some playing around and creating the ctags for my project (Rails) manually, I saw the settings on the config site again. Atom 1.0.19
