### ISSUE TITLE
Stopped: Build more than 10 seconds

### ISSUE THREAD

**Issue by Nitrino** [yongkangchen/atom-ctags#173]
version 5.0.0 in usual ruby project

```
Stopped: Build more than 10 seconds, check if /Users/nitrino/develop/makmak/code contain too many files.
Suggest that add CmdArgs at atom-ctags package setting, example:
--exclude=some/path --exclude=some/other
```

**Comment by ErikFontanel** [comment]
The solution is in the error ;)
Add as many files/paths to `Cmd Args` in the Atom Ctags settings as you like to exclude from indexing. Each excluded path needs to be prefixed with the --exclude flag eg;
`--exclude=node_modules --exclude=*.somefileextension`

see the [ctags manual](http://ctags.sourceforge.net/ctags.html) for all arguments and advanced use.

**Comment by aurovrata** [comment]
incease the time out to 30 sec, it worked for me... however the .tags file created is huge and crashes the window on restart (see [this issue](https://github.com/yongkangchen/atom-ctags/issues/183))
