### ISSUE TITLE
Tag file locations

### ISSUE THREAD

**Issue by B1scuit** [yongkangchen/atom-ctags#194]
At present this package is working exactly as intended for me, however, I find .tag files in my project root, which is normally a git repo so git is trying to add and commit up the tag files and I have to work around these when committing.

Would it be an idea to have a path setting where we can select the location of these files? It would be ideal to be able to put these in the vendor folder that is ignored.

<img width="189" alt="screen shot 2017-08-11 at 08 43 15" src="https://user-images.githubusercontent.com/2174593/29204846-2cb5f25c-7e71-11e7-9681-31cc582627b4.png">

**Comment by theonedemon** [comment]
Use git global settings `gitexcludes`
cat ~/.gitexcludes
```
.ctags
.tags*
.tags_swap

```

cat ~/.gitconfig
```
[core]
    excludesfile = ~/.gitexcludes
```
