### ISSUE TITLE
ctrl+click for "go to declaration"

### ISSUE THREAD

**Issue by yongkangchen** [yongkangchen/atom-ctags#2]
from @Nicolab

> Suggestion: it would be more efficient to make a ctrl+click like in Eclipse IDE for "go to declaration"

as 

> https://github.com/atom/symbols-view/issues/18

**Comment by steelbrain** [comment]
I think this should be reopened as alt+click event is not triggered in the latest Atom, it instead highlights the options in the topbar. Pressing ctrl+alt+click triggers the event but I don't think it's a good way of doing it.

**Comment by vapask** [comment]
Also alt-click is not working in ubuntu, because alt-click triggers window move (affects not only ubuntu I assume). Maybe ctrl+shift+click will work?

**Comment by davidcroda** [comment]
+1, this does not work in Ubuntu and should have a different default bind.

**Comment by n3bulous** [comment]
I would like to suggest revisiting this binding.  It would be great to allow configuring the keystrokes for go-to-declaration since alt-click also collides w/ sublime style column select.

**Comment by contentfree** [comment]
@n3bulous +1. Please allow the mouse binding to be configurable. I too use the sublime-style column select and this busts it (or vice versa, if you please)

**Comment by mefynn** [comment]
how about alt+cmd+ click?

**Comment by FDiskas** [comment]
:grinning: OK OK stop this!!!.
All other editors is using ```Ctrl + Click```. Do not invent the wheel again.

**Comment by steelbrain** [comment]
Hey, just to put it out there. I've created [`declarations`](https://atom.io/packages/declarations) package, it's the base package for declarations and is pretty neat and consistent across providers

**Comment by webdevbyjoss** [comment]
Subscribing for `Ctrl + Click` possibility (configurable?)

**Comment by sebastian-nowak** [comment]
+1, `ctrl + click` is a standard in different editors

**Comment by isaacdeveloper** [comment]
+1000

**Comment by nakulsaini** [comment]
+1 ctrl + click

**Comment by xtrycatchx** [comment]
+1 for ctrl + click

**Comment by mxchange** [comment]
Is there a way to disable this? I'm constantly double clicking a word and I'm used to already press `ctrl` while clicking to do `ctrl+c` to copy, which then will go to definition instead of copying.

**Comment by Rictus** [comment]
+1 for ctrl + click.
Even if ctrl+click is used for the multiple cursor feature, I think we can have have a goto-definition on this same shortcut like in Wbestorm (or any Jetbrains IDE).

**Comment by Surroot** [comment]
Any news on this?
I would highly appreciate this function like in Eclipse: F3 to jump to definition and F2 to go back to previous...

**Comment by DedMorozzz** [comment]
+1 for ctrl + click

**Comment by rolzing** [comment]
+1 cmd+click or ctrl+click
