### ISSUE TITLE
how does this package work?

### ISSUE THREAD

**Issue by robkorv** [yongkangchen/atom-ctags#43]
Hi,

![Alt Text](https://cloud.githubusercontent.com/assets/704762/3483867/e0bac2ee-0397-11e4-89c1-70689f6b8ff3.gif)

Pretty neat animation :heart:, but how do I get it working?
I have the ctags command installed... now what?

What do I need to put in?:
* Cmd (just `ctags` does nothing)
* Cmd Args

The README does say `--fields=+KSn` about Extra Tag Files, but I get an error `Error: ENOENT, open '--fields=+KSn'`.

**Comment by npassaro** [comment]
I have a custom made script that not only generates tags for the project but also for ruby as a whole when a given file is not present.

1. Is it possible to execute that in the project?
2. How do I know where the command is being executed?

**Comment by flynfish** [comment]
I'm also a bit confused. I've installed and had to change the default timeout to 30 seconds, along with adding a bunch of excludes in the extra tags. It still doesn't seem like its working...

If I click Go to Declaration of a class name which is defined in a different file, it won't find it.

**Comment by flynfish** [comment]
And I just figured it out... I was right clicking the class name before making sure that the cursor was actually located on the class name.
