### ISSUE TITLE
Add priority stuff to suggestions

### ISSUE THREAD

**Issue by yongkangchen** [yongkangchen/atom-ctags#5]
> https://github.com/saschagehlich/autocomplete-plus/issues/29
> As propsed by @pjv, we should add some priority stuff to the suggestions:
> - matches from the current language syntax file
> - matches from snippets for the current language
> - matches from word list from the current file buffer

**Comment by jdanbrown** [comment]
Here's a PR that might help you out. It doesn't prioritize the symbols ordering as requested above, but it does let you match against the file path in addition to the symbol name, which I needed after adding all of my python dependencies into my tags file.
- https://github.com/yongkangchen/atom-ctags/pull/204
