### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by AlexKR** [yongkangchen/atom-ctags#52]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/AlexKR/.atom/packages/atom-ctags/lib/main.coffee:43:9)
```

**Comment by eleidan** [comment]
Got the same issue.
OS: Ubuntu 14.04
Atom: 0.176.0

**Comment by stinger** [comment]
Same issue, OSX, Atom 0.177.0
