### ISSUE TITLE
"Auto Build Tags When Active" after each save?

### ISSUE THREAD

**Issue by mndrix** [yongkangchen/atom-ctags#54]
When I enable the configuration "Auto Build Tags When Active", should the tags file be rebuilt each time I save a file within my project?

I thought that's what the configuration did, but it seems not to happen that way.  So far, the configuration only seems to rebuild my tags file when I open Atom on my project for the first time.

**Comment by yongkangchen** [comment]
It means auto build tags when atom-ctags package active.
