### ISSUE TITLE
Update Package To Use New autocomplete-plus API

### ISSUE THREAD

**Issue by joefitzgerald** [yongkangchen/atom-ctags#57]
Please:

* Switch to the new `autocomplete-plus` `1.0.0` API: https://github.com/atom-community/autocomplete-plus/wiki/Provider-API
* Move away from having 1 provider instance for every editor instance

**Comment by joefitzgerald** [comment]
Hey @yongkangchen, I am going to remove the legacy API from autocomplete-plus in 1 week, on February 11th, 2015. Please let me know if you need more time to make the updates to atom-ctags; after that time, if you haven't made the changes, atom-ctags will cease to function.

**Comment by yongkangchen** [comment]
Hey @joefitzgerald  I will be free since tomorrow, and I need about two days to update atom-ctags. 
It would be great to delay on Feb 13th, 2015.  Thanks.

**Comment by joefitzgerald** [comment]
OK @yongkangchen, watch https://github.com/atom-community/autocomplete-plus/pull/253 - when it is merged, the API is removed. I still have to fix tests.

**Comment by joefitzgerald** [comment]
And yes, I will wait till the 13th.
