### ISSUE TITLE
Ability to reference relative paths for extra tag files

### ISSUE THREAD

**Issue by geoffharcourt** [yongkangchen/atom-ctags#58]
Apologies if this is already possible, but after a bunch of searching and Googling I can't figure out how to do this.

I keep my tags files for projects in `./.git/tags`. When I enter a path like that as an extra tag file, Atom gives an error about the file not being found, and the tag does not get incorporated into autocomplete suggestions. Is it possible to suggestion relative paths?

(also have a question about globs for tag paths for dependency libraries, but if I'm missing something that may already be here).

**Comment by noseglid** [comment]
+1. 

I definitely do not have the same tags file for all projects I code on. Having them relative to the project root would allow me to set this to simply `tags` and the tags file in the current project would do the magics for me.

**Comment by TuckerWhitehouse** [comment]
:+1:  Waisted a fair bit of time trying to figure out why my vendor/.tags file wasn't being loaded, would be very convenient to reference project relative files.

**Comment by stefansedich** [comment]
+1 just got bitten by this, is there any way to make it happen at the moment? I was hoping I could use a glob path to point to the auto generated tags I have within my gems folder, something like ~/foo/gems/**/tags but that did not work either.

**Comment by benwoodward** [comment]
+1
