### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by samirotiv** [yongkangchen/atom-ctags#73]
Sorry to bother you. :) Just creating the issues so that anybody else experiencing the same knows about it.

Requiring `$$` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{$$} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\Samir\AppData\Local\atom\app-0.189.0\resources\app\exports\atom.js:49:9)
Object.<anonymous> (C:\Users\Samir\.atom\packages\atom-ctags\lib\symbols-view.coffee:1:1)
```

**Comment by yongkangchen** [comment]
fixed by 4bf699d.
