### ISSUE TITLE
Invisible search keyword in Symbol view

### ISSUE THREAD

**Issue by jinksong** [yongkangchen/atom-ctags#75]
1. Press Ctrl+r to start searching symbols
2. Type any keyword

![image](https://cloud.githubusercontent.com/assets/5316839/7099531/8ac740a8-dfa9-11e4-94f5-27ec05b59ea8.png)

It shows the symbol list as typed, but the keyword is completely invisible.

**Comment by yongkangchen** [comment]
fixed by 4bf699d
