### ISSUE TITLE
请问有使用该插件的教程么。

### ISSUE THREAD

**Issue by JinLingChristopher** [yongkangchen/atom-ctags#76]
你好，我是才使用编辑器编写代码的菜鸟，第一次使用ctags。我主要用于编写cuda和opencv的图像处理程序。请问如何使用该插件实现功能，我已经搜了很多方法都没有关于该插件的使用说明，如果可以的话，能否点拨一下。谢谢，不胜感激。

**Comment by yongkangchen** [comment]
参见：https://cloud.githubusercontent.com/assets/704762/3483867/e0bac2ee-0397-11e4-89c1-70689f6b8ff3.gif

**Comment by yongkangchen** [comment]
```
Install
You can install atom-ctags using the Preferences pane. And please Make sure that autocomplete-plus already installed.
```
