### ISSUE TITLE
ocaml.ml from Ace: failed to parseTagLine: 

### ISSUE THREAD

**Issue by crazyh** [yongkangchen/atom-ctags#80]
atom-ctags fails to build tags file for Ace

command: @/home/sergey-zolotorev/workspace/depresso/atom/.atom/packages/atom-ctags/vendor/ctags-linux --options=/home/sergey-zolotorev/workspace/depresso/atom/.atom/packages/atom-ctags/lib/.ctags --fields=+KSn --excmd=p -R -f - /home/sergey-zolotorev/workspace/iris@failed to parseTagLine: @"Ocaml\t/home/sergey-zolotorev/workspace/iris/src/components/bower_components/ace-builds/demo/kitchen-sink/docs/ocaml.ml\t1;\"\tmodule\tline:1"@

**Comment by yongkangchen** [comment]
This should not exists in latest version.

**Comment by crazyh** [comment]
Still present in 3.2.0.

Output of `/home/sergey-zolotorev/.atom/packages/atom-ctags/vendor/ctags-linux --options=/home/sergey-zolotorev/.atom/packages/atom-ctags/lib/.ctags --fields=+KSn --excmd=p -R -f - /tmp/ocaml.ml`:

    ctags-linux: Warning: Language "Go" already defined
    Ocaml	/tmp/ocaml.ml	1;"	module	line:1
    Return	/tmp/ocaml.ml	/^     struct exception Return of t end$/;"	Exception	line:8
    return	/tmp/ocaml.ml	/^  let return = { return = (fun x -> raise (M.Return x)); } in$/;"	var	line:10
    sum_until_first_negative	/tmp/ocaml.ml	/^let sum_until_first_negative list =$/;"	var	line:15
    with_return	/tmp/ocaml.ml	/^let with_return (type t) (f : _ -> t) =$/;"	var	line:6

`/home/sergey-zolotorev/.atom/packages/atom-ctags/vendor/ctags-linux --version`:

    Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
    Compiled: Nov  9 2011, 17:42:21
    Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
    Optional compiled features: +wildcards, +regex

`apm ls | grep atom-ctags`:

    ├── atom-ctags@3.2.0
