### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [yongkangchen/atom-ctags#93]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version of this package:

1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
1. Use Cursor::getScopeDescriptor() instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by yongkangchen** [comment]
Fixed at #89 and #87, release in v4.1.0
