### ISSUE TITLE
Custom cmd does not seem to work

### ISSUE THREAD

**Issue by crucialfelix** [yongkangchen/atom-ctags#94]
```
Cmd          ctags
Cmd Args: -e -R --languages=python --exclude="__init__.py" -o TAGS . 
```

Where are you looking for the tags file ? If I make a custom command then where does it output to ? Or is it supposed to not use -o and should just output ?

Ideally I think it should use normal ctags convention and include my ~/.ctags or let me specify a ctags file.

I've also tried setting the command to `make ctags` which would do the same thing.

I tried setting extra tags files to `TAGS`

I get an error like this displayed in an Atom ctags panel:

```
Error: ENOENT: no such file or directory, open 'TAGS'
please create a new issue:
command: @ctags -e -R --languages=python --exclude="__init__.py" --options=/Users/crucial/.atom/packages/atom-ctags/lib/.ctags --fields=+KSn --excmd=p -R -f - /Users/crucial/Sites/nsbuildout@failed to parseTagLine: @"\f"@
failed to parseTagLine: @"/Users/crucial/Sites/nsbuildout/__init__.py,0"@
```

And it always says "No symbols found" when I do a project-symbols lookup.

thank you !

**Comment by yongkangchen** [comment]
It can not use `-o`

**Comment by crucialfelix** [comment]
Like this?
```
Cmd          ctags
Cmd Args: -e -R --languages=python --exclude="__init__.py"
```

**Comment by ypresto** [comment]
--exclude=foobar is also not working. It does not pass any args to ctags command.

There seems to be a mistake on `@cmdArgs` and `cmdArgs` (local variable) is right.
 https://github.com/yongkangchen/atom-ctags/blob/master/lib/tag-generator.coffee#L45

**Comment by yongkangchen** [comment]
Release in v4.1.1 Thanks @ypresto again

**Comment by crucialfelix** [comment]
thanks. I'll try it again

Does this work at all: to use my ~/.ctags or let me specify a ctags file for a project ?

**Comment by yongkangchen** [comment]
@crucialfelix `~/.ctags` is supported before this fixed whether with or without `Cmd Args`.
Of course this fixed `Cmd Args`, so you can specify a ctags file for a project
