### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by jingpengwu** [yongkangchen/atom-ctags#95]
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

ubuntu 14.04
Atom 0.198.0

all the error message:

Deprecated calls
atom-ctags (2 deprecations)
The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
Called 1 timeCreate Issue on atom-ctags repo
Package.activateResources - /usr/share/atom/resources/app.asar/src/package.js:323:19
<unknown> - /usr/share/atom/resources/app.asar/src/package.js:219:21
Package.measure - /usr/share/atom/resources/app.asar/src/package.js:167:15
Package.activate - /usr/share/atom/resources/app.asar/src/package.js:215:14
Use Cursor::getScopeDescriptor() instead
Called 1 timeCreate Issue on atom-ctags repo
Cursor.getScopes - /usr/share/atom/resources/app.asar/src/cursor.js:745:12
FileView.getCurSymbol - /usr/people/jingpeng/.atom/packages/atom-ctags/lib/file-view.coffee:69:14
FileView.goto - /usr/people/jingpeng/.atom/packages/atom-ctags/lib/file-view.coffee:85:14
atom-workspace.<anonymous> - /usr/people/jingpeng/.atom/packages/atom-ctags/lib/main.coffee:58:24

**Comment by mohnish** [comment]
I'm having the same issue with **atom-ctags v3.2.0** and **Atom v0.204.0**

**Comment by yongkangchen** [comment]
Thanks, alread fixed. please wait for the next release of atom-ctags.
