### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filename.es6' of undefined

### ISSUE THREAD

**Issue by averrin** [yongkangchen/atom-ctags#97]
Every time when i press ctrl+r in es6 file and sometimes in js files

Uncaught TypeError: Cannot read property 'template.es6' of undefined
/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:99
Hide Stack Trace
TypeError: Cannot read property '/home/user/projects/app-template/src/zodiac/template/template.es6' of undefined
  at /home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:99:26
  at /home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:92:7
  at exit (/home/user/.atom/packages/atom-ctags/lib/tag-generator.coffee:62:5)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

in console:

[atom-ctags:rebuild] start @/home/user/projects/app-template/src/zodiac/template/template.es6@ tags...
/home/user/.atom/packages/atom-ctags/lib/tag-generator.coffee:81 atom-ctags: command error, ctags-linux: Warning: Language "Go" already defined
 /home/user/projects/app-template/.tags1
/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:137 [atom-ctags:rebuild] command done @/home/user/projects/app-template/src/zodiac/template/template.es6@ tags. cost: 59ms
/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:70 [atom-ctags:readTags] /home/user/projects/app-template/.tags1 start...
/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:140 [atom-ctags:rebuild] parse end @/home/user/projects/app-template/src/zodiac/template/template.es6@ tags. cost: 0ms
/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:152 Uncaught TypeError: Cannot read property '/home/user/projects/app-template/src/zodiac/template/template.es6' of undefined
index.js:14 Unhandled promise rejection Promise with error: TypeError: undefined is not a function
/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:91 [atom-ctags:readTags] /home/user/projects/app-template/.tags1 cost: 87ms

**Comment by ascariandrea** [comment]
I'm experiencing the same problem.

**Comment by yongkangchen** [comment]
Duplicate with #101 and fixed in v4.1.2, please update and try again.
